using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace KSP_LogiRGB.Layout.LayoutProviders.Windows
{
    public class WindowsLayoutProvider : ILayoutProvider
    {
        public enum VirtualKey : ushort
        {
            None = 0x00,
            Backspace = 0x08,
            Tab = 0x09,
            Clear = 0x0C,
            Return = 0x0D,
            Pause = 0x1B,
            Escape = 0x13,
            Space = 0x20,
            Quote = 0xDE,
            Plus = 0xBB,
            Comma = 0xBC,
            Minus = 0xBD,
            Period = 0xBE,
            Slash = 0xBF,
            Alpha0 = 0x30,
            Alpha1 = 0x31,
            Alpha2 = 0x32,
            Alpha3 = 0x33,
            Alpha4 = 0x34,
            Alpha5 = 0x35,
            Alpha6 = 0x36,
            Alpha7 = 0x37,
            Alpha8 = 0x38,
            Alpha9 = 0x39,
            Semicolon = 0xBA,
            LeftBracket = 0xDB,
            Backslash = 0xDC,
            RightBracket = 0xDD,
            BackQuote = 0xC0,
            A = 0x41,
            B = 0x42,
            C = 0x43,
            D = 0x44,
            E = 0x45,
            F = 0x46,
            G = 0x47,
            H = 0x48,
            I = 0x49,
            J = 0x4A,
            K = 0x4B,
            L = 0x4C,
            M = 0x4D,
            N = 0x4E,
            O = 0x4F,
            P = 0x50,
            Q = 0x51,
            R = 0x52,
            S = 0x53,
            T = 0x54,
            U = 0x55,
            V = 0x56,
            W = 0x57,
            X = 0x58,
            Y = 0x59,
            Z = 0x5A,
            Delete = 0x2E,
            UpArrow = 0x26,
            DownArrow = 0x28,
            RightArrow = 0x27,
            LeftArrow = 0x25,
            Insert = 0x2D,
            Home = 0x24,
            End = 0x23,
            PageUp = 0x21,
            PageDown = 0x22,
            F1 = 0x70,
            F2 = 0x71,
            F3 = 0x72,
            F4 = 0x73,
            F5 = 0x74,
            F6 = 0x75,
            F7 = 0x76,
            F8 = 0x77,
            F9 = 0x78,
            F10 = 0x79,
            F11 = 0x7A,
            F12 = 0x7B,
            F13 = 0x7C,
            F14 = 0x7D,
            F15 = 0x7E,
            Numlock = 0x90,
            CapsLock = 0x14,
            ScrollLock = 0x91,
            RightShift = 0xA1,
            LeftShift = 0xA0,
            RightControl = 0xA3,
            LeftControl = 0xA2,
            RightAlt = 0xA5,
            LeftAlt = 0xA4,
            LeftWindows = 0x5B,
            RightWindows = 0x5C,
            Help = 0x2F,
            Print = 0x2A,
            SysReq = 0x2C,
            Menu = 0x5D
        }

        public KeyCode ConvertToQwertyCode(KeyCode nativeCode)
        {
            throw new NotImplementedException();
        }
    }
}